FROM php:7.1-fpm-alpine
RUN cd /tmp \
  && mkdir "/tmp/php-sessions" \
  && chown -R www-data:www-data "/tmp/php-sessions" \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && apk add --no-cache zlib-dev libexif-dev graphicsmagick-dev autoconf autoconf gcc g++ libtool make \
  && docker-php-ext-install opcache pdo pdo_mysql zip exif \
  && echo "\n" | pecl install gmagick-2.0.4RC1 \
  && docker-php-ext-enable gmagick \
  && apk del autoconf g++ libtool make \
  && curl https://raw.githubusercontent.com/composer/getcomposer.org/1b137f8bf6db3e79a38a5bc45324414a6b1f9df2/web/installer | php -- --quiet \
  && mv composer.phar /usr/local/bin/composer
